version: '3'

services:

  backend:
    build: ./backend
    entrypoint: ./backend/.docker/entrypoint.sh
    container_name: micro-mapping-backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - rabbitmq_network

  frontend:
    build: ./frontend
    entrypoint: ./frontend/.docker/entrypoint.sh
    container_name: micro-mapping-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3002
    ports:
      - 3002:3002
    volumes:
      - .:/home/node/app
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: micro-mapping-db
    restart: always
    tty: true
    ports:
      - "33007:3306"
    volumes:
      - ./backend/.docker/dbdata:/var/lib/mysql
      - ./backend/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  rabbitmq_network:
    external: true
